### ISSUE TITLE
nexmark fails on latest master [e50067c]

### ISSUE THREAD

**Issue by gz** [vmware/database-stream-processor#204]
rev: [e50067c](https://github.com/vmware/database-stream-processor/commit/e50067c8890cbc4e32390c632ef864f87b029b34)

cargo +nightly bench --bench nexmark --features with-nexmark -- --first-event-rate=10000000 --max-events=1000000 --cpu-cores 8  --num-event-generators 6 --source-buffer-size 10000 --input-batch-size 40000

```
1,000,000 / 1,000,000 [=====================================================================] 100 % 2,387,494.1547/s 0sStarting q17 bench of 1000000 events...
40,000 / 1,000,000 [==>-----------------------------------------------------------------------] 4 % 1,745,934.5695/s 1sthread 'thread 'dbsp-worker-3' panicked at 'index out of bounds: the len is 373 but the index is 18446744073709551615', src/trace/layers/ordered.rsthread 'dbsp-worker-1' panicked at 'index out of bounds: the len is 377 but the index is 18446744073709551615', dbsp-worker-5thread '' panicked at 'dbsp-worker-4index out of bounds: the len is 373 but the index is 18446744073709551615' panicked at '', src/trace/layers/ordered.rssrc/trace/layers/ordered.rs::914:914914::2222
index out of bounds: the len is 371 but the index is 18446744073709551615
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
', src/trace/layers/ordered.rs:914:22:
22
thread 'dbsp-worker-7' panicked at 'index out of bounds: the len is 377 but the index is 18446744073709551615', src/trace/layers/ordered.rsthread 'dbsp-worker-6' panicked at 'index out of bounds: the len is 374 but the index is 18446744073709551615', src/trace/layers/ordered.rs:914:22
:914:22
thread 'dbsp-worker-0' panicked at 'index out of bounds: the len is 381 but the index is 18446744073709551615', src/trace/layers/ordered.rs:914:22
thread 'dbsp-worker-2' panicked at 'index out of bounds: the len is 380 but the index is 18446744073709551615', src/trace/layers/ordered.rs:914:22
thread 'benchmark_consumer' panicked at 'called `Result::unwrap()` on an `Err` value: Runtime(WorkerPanic(0))', benches/nexmark/main.rs:67:29
```

**Comment by gz** [comment]
Maybe we should run some small amount of data through the queries during CI

**Comment by ryzhyk** [comment]
@Kixiron , looks like this is crashing in `Consumer`:

```
   0: rust_begin_unwind
             at /rustc/8b0c05d9ad7121cdb97600f261bcd5f04c8db20d/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/8b0c05d9ad7121cdb97600f261bcd5f04c8db20d/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/8b0c05d9ad7121cdb97600f261bcd5f04c8db20d/library/core/src/panicking.rs:84:5
   3: dbsp::trace::layers::ordered::OrderedLayerValues<V,R>::new
   4: <dbsp::trace::layers::ordered::OrderedLayerConsumer<K,V,R,O> as dbsp::trace::cursor::Consumer<K,V,R,()>>::next_key
             at ./src/trace/layers/ordered.rs:829:15
   5: <dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSetConsumer<K,V,R,O> as dbsp::trace::cursor::Consumer<K,V,R,()>>::next_key
             at ./src/trace/ord/indexed_zset_batch.rs:536:31
   6: <dbsp::operator::filter_map::FilterVals<CI,CO,F> as dbsp::circuit::operator_traits::UnaryOperator<CI,CO>>::eval_owned
             at ./src/operator/filter_map.rs:466:37
   7: <dbsp::circuit::circuit_builder::UnaryNode<C,I,O,Op> as dbsp::circuit::circuit_builder::Node>::eval
             at ./src/circuit/circuit_builder.rs:2182:30
   8: dbsp::circuit::circuit_builder::Circuit<P>::eval_node
             at ./src/circuit/circuit_builder.rs:1091:18
   9: dbsp::circuit::schedule::dynamic_scheduler::Inner::step
             at ./src/circuit/schedule/dynamic_scheduler.rs:365:21
  10: <dbsp::circuit::schedule::dynamic_scheduler::DynamicScheduler as dbsp::circuit::schedule::Scheduler>::step
             at ./src/circuit/schedule/dynamic_scheduler.rs:400:9
  11: <dbsp::circuit::schedule::OnceExecutor<S> as dbsp::circuit::schedule::Executor<P>>::run
             at ./src/circuit/schedule/mod.rs:148:9
  12: dbsp::circuit::circuit_builder::CircuitHandle::step
             at ./src/circuit/circuit_builder.rs:3106:9
  13: dbsp::circuit::dbsp_handle::<impl dbsp::circuit::runtime::Runtime>::init_circuit::{{closure}}
             at ./src/circuit/dbsp_handle.rs:79:38
  14: dbsp::circuit::runtime::Runtime::run::{{closure}}::{{closure}}
             at ./src/circuit/runtime.rs:155:21
```

**Comment by Kixiron** [comment]
@ryzhyk Can you try with [this branch](https://github.com/Kixiron/database-stream-processor/tree/all-consuming-panic), I believe I fixed it there
