### ISSUE TITLE
Out-of-bounds access in `consolidate_paired_slices`

### ISSUE THREAD

**Issue by utaal** [vmware/database-stream-processor#277]
On https://github.com/vmware/database-stream-processor/commit/50e58aa34d66b3fbaa6f7481a90af2ae870f132d, tests segfault on the unchecked access for `idx1` at https://github.com/vmware/database-stream-processor/blob/50e58aa34d66b3fbaa6f7481a90af2ae870f132d/src/trace/consolidation/mod.rs#L185

I temporarily replaced the unchecked access with regular `Index`, and got errors like:
```
---- operator::distinct::test::distinct_trace_test_mt stdout ----
thread 'dbsp-worker-0' panicked at 'index out of bounds: the len is 3 but the index is 8070450532586684418', src/trace/consolidation/mod.rs:186:13
thread 'operator::distinct::test::distinct_trace_test_mt' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/operator/distinct.rs:696:25
```
Which looks like the indices are nonsensical; maybe underflow?

These are all the failures:
```
failures:
    operator::aggregate::test::proptest_aggregate_test_mt
    operator::aggregate::test::proptest_aggregate_test_st
    operator::distinct::test::distinct_trace_test_mt
    operator::join::test::join_trace_test
    operator::join::test::propagate_nested_test
    operator::recursive::test::reachability
    operator::recursive::test::reachability2
    trace::consolidation::tests::fill_indices
    trace::consolidation::tests::test_consolidate_paired_slices
```

I don't yet know why this doesn't happen on CI. One potential environment difference is that I'm on Apple Silicon / M1.

**Comment by utaal** [comment]
Ok, the culprit seems to be that `fill_indices_aarch64_neon` https://github.com/vmware/database-stream-processor/blob/50e58aa34d66b3fbaa6f7481a90af2ae870f132d/src/trace/consolidation/fill_indices.rs#L202 is selected but it produces an invalid result (at least) for Apple Silicon / M1.
